--Задача 1--
SELECT CUST_NUM
FROM [dbo].[CUSTOMERS]
WHERE CREDIT_LIMIT = (
    SELECT MAX(CREDIT_LIMIT) 
    FROM [dbo].[CUSTOMERS]


)--Задача 2--
SELECT O.ORDER_ID, O.CUST_NUM, O.ORDER_DATE, O.ORDER_AMOUNT
FROM [dbo].[ORDERS] O
JOIN [dbo].[CUSTOMERS] C ON O.CUST_NUM = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (
    SELECT MAX(CREDIT_LIMIT)
    FROM [dbo].[CUSTOMERS]
)


--Задача 3--
SELECT TOP 1 O.ORDER_ID, O.CUST_NUM, O.ORDER_DATE, O.ORDER_AMOUNT
FROM [dbo].[ORDERS] O
JOIN [dbo].[CUSTOMERS] C ON O.CUST_NUM = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (
    SELECT MAX(CREDIT_LIMIT)
    FROM [dbo].[CUSTOMERS]
)
ORDER BY O.ORDER_DATE DESC
