SELECT CUST_NUM
FROM dbo.CUSTOMERS3
WHERE CREDIT_LIMIT = (
    SELECT MAX(CREDIT_LIMIT)
    FROM dbo.CUSTOMERS3
);



SELECT O.ORDER_NUM, O.CUST
FROM dbo.ORDERS3 O
JOIN dbo.CUSTOMERS3 C ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (
    SELECT MAX(CREDIT_LIMIT)
    FROM dbo.CUSTOMERS3
);



SELECT TOP 1 O.ORDER_NUM, O.CUST, O.ORDER_DATE
FROM dbo.ORDERS3 O
JOIN dbo.CUSTOMERS3 C ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (
    SELECT MAX(CREDIT_LIMIT)
    FROM dbo.CUSTOMERS3
)
ORDER BY O.ORDER_DATE DESC;





