Use WebStor; 
--ЗАВДАННЯ 1--
SELECT C.CUST_NUM
FROM dbo.CUSTOMERS C
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);

--Завдання 2--
SELECT O.ORDER_NUM
FROM dbo.ORDERS O
INNER JOIN dbo.CUSTOMERS C ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS);

--Завдання 3--
SELECT O.ORDER_NUM
FROM dbo.ORDERS O
INNER JOIN dbo.CUSTOMERS C ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
AND O.ORDER_DATE = (SELECT MAX(ORDER_DATE) FROM dbo.ORDERS WHERE CUST = O.CUST);