use WebStor

--Task 1--

SELECT CUST_NUM
FROM [dbo].[CUSTOMERS]
WHERE CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS]);

--Task 2--

SELECT o.[CUST]
FROM [dbo].[ORDERS] o
JOIN [dbo].[CUSTOMERS] c ON o.CUST= c.CUST_NUM
WHERE c.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS]);


--Task 3--

SELECT TOP 1 o.CUST
FROM [dbo].[ORDERS] o
JOIN [dbo].[CUSTOMERS] c ON o.CUST = c.CUST_NUM
WHERE c.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS])
ORDER BY o.ORDER_DATE DESC;
